### ISSUE TITLE
Some themes are not shown

### ISSUE THREAD

**Issue by ronnix** [m-allanson/pelican-themes#3]
Some themes have a preview image named `preview.png` for example, and are not matched by the current regex:

```js
var regex = /^(screenshot)([\w-_]*).(png)$/i;
```

**Comment by m-allanson** [comment]
I've been meaning to update this for a long time, this has prompted me to do so.  Thanks!

There's a new version of the site live now, which is also pushed to github.  This new version has a more permissive regex, searching for `.png` or `.jpg` files in the root of the theme folder.  This catches more images than before, although still not all of them.  The themes without screenshots are listed at the bottom of the page so it's possible to manually check which ones are missing.

**Comment by m-allanson** [comment]
If the DNS hasn't kicked in yet, you can see the updated version running here: http://pelicanthemes-prod.herokuapp.com/

**Comment by ronnix** [comment]
Awesome! Thanks for this useful service.
