### ISSUE TITLE
Question: Customized 404 page

### ISSUE THREAD

**Issue by rosirioja** [m-allanson/pelican-themes#5]
Hi,
I'm currently using your pelican-themes. May I know how to implement 404 page in every theme?
Thanks

**Comment by m-allanson** [comment]
Hi @rosirioja, sorry I don't understand your question. This project is not built with Pelican or any Pelican themes - it only lists out screenshots from the themes section of the Pelican repository. 

If you want to create a 404 page for your own Pelican blog, you could try the instructions listed here: http://docs.getpelican.com/en/3.6.3/tips.html#custom-404-pages, or have a look at the themes on the Pelican GitHub repo here: https://github.com/getpelican/pelican-themes

Does that help?

**Comment by rosirioja** [comment]
Hi,
Sure. I'll check this out. Thanks for your help! :)

Thanks,

Rosiliza R. Rioja

**Comment by m-allanson** [comment]
:+1:
